"""Crear tabla de alumnos

Revision ID: 3e76f017c540
Revises: 33b0cf898422
Create Date: 2024-10-17 07:54:07.603024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e76f017c540'
down_revision = '33b0cf898422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumnos')
    # ### end Alembic commands ###
