from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4c934f29354d'
down_revision = '3e76f017c540'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clases', schema=None) as batch_op:
        # Agregar columna 'maestro_id'
        batch_op.add_column(sa.Column('maestro_id', sa.Integer(), nullable=False))

        # Crear la clave foránea, correctamente con 5 argumentos
        batch_op.create_foreign_key(
            'fk_clases_maestro',  # Nombre de la clave foránea
            'users',              # Tabla referenciada
            ['maestro_id'],       # Columna local
            ['id']                # Columna en la tabla referenciada
        )

        # Agregar las columnas 'horario_inicio' y 'horario_fin'
        batch_op.add_column(sa.Column('horario_inicio', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('horario_fin', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clases', schema=None) as batch_op:
        # Eliminar la clave foránea
        batch_op.drop_constraint('fk_clases_maestro', type_='foreignkey')

        # Eliminar las columnas añadidas
        batch_op.drop_column('horario_fin')
        batch_op.drop_column('horario_inicio')
        batch_op.drop_column('maestro_id')
    # ### end Alembic commands ###
