"""Crear tablas de parciales, tareas, pruebas y examenes

Revision ID: 8f4500ceed7a
Revises: 4c934f29354d
Create Date: 2024-10-17 08:55:03.186150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4500ceed7a'
down_revision = '4c934f29354d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['clases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('puntaje_maximo', sa.Float(), nullable=False),
    sa.Column('parcial_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('puntaje_obtenido', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['parcial_id'], ['parciales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pruebas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('puntaje_maximo', sa.Float(), nullable=False),
    sa.Column('parcial_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('puntaje_obtenido', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['parcial_id'], ['parciales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('puntaje_maximo', sa.Float(), nullable=False),
    sa.Column('parcial_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('puntaje_obtenido', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['parcial_id'], ['parciales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    op.drop_table('pruebas')
    op.drop_table('examenes')
    op.drop_table('parciales')
    # ### end Alembic commands ###
